version: '3'

networks:
  nginx-php74-node:

services:
  postgres12-service:
    container_name: postgres-container
    image: postgres:12.4-alpine
    restart: on-failure
    volumes:
    - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: educamp
      POSTGRES_USER: sf_user
      POSTGRES_PASSWORD: random_password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - nginx-php74-node

  #nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - node-service
    networks:
      - nginx-php74-node
  #php
  php74-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php74-container
    ports:
      - "9000:9000"
    depends_on:
      - postgres12-service
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php74-node
  #node
  node-service:
    image: node:latest
    container_name: node-container
    volumes:
      - ./app:/var/www/project
    working_dir: /var/www/project
    networks:
      - nginx-php74-node
