doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
#        dbname:               test
#        host:                 postgres
#        port:                 5432
#        user:                 sf_user
#        password:             random_password
#        driver:               pdo_mysql
        # if the url option is specified, it will override the above config
#        url:                  postgresql://sf_user:random_password@localhost:5432/test
        # the DBAL driverClass option

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '12.4'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
